config/routes.rb
Rails.application.routes.draw do
  resources :categories
  
  resources :articles
  root 'home#index'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  validates :tittle, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]
  before_action :require_user, except: [:show, :index]
  before_action :require_same_user, only: [:edit, :update, :destroy]
  # GET /articles or /articles.json
  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)
    @article.user = current_user
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:tittle, :description)
    end
    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only edit or delete your own article"
        redirect_to @article
      end
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="page-content">
  <h2 class="text-center mt-4"><%= @article.tittle %></h2>
  <div class="container">
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
           <% if article.user %>
              by <%= link_to article.user.username, user_path(article.user) %>
               <%= link_to gravatar_for(@article.user), user_path(@article.user) %>
            <% end %>
          </div>
          <div class="card-body">
            <div class="card-text text-left"><%= simple_format(@article.description) %></div>
              <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(@article), class: "btn btn-outline-danger",data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(@article.created_at) %> ago, 
            edited <%= time_ago_in_words(@article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="container">
  

  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @article %>
      <%= form_with(model: @article, class: "shadow p-3 mb-3 form-css rounded", local: true) do |f| %>
        <div class="form-group row  ">
          <%= f.label :tittle, class: "col-2 col-form-label text-light" %>
          <div class="col-10">
            <%= f.text_field :tittle, class: "form-control shadow rounded index-form", placeholder: "Title of article" %>
          </div>
        </div>
   <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-10"> 
            <%= f.text_area :description, rows: 10, class: "form-control shadow rounded index-form", placeholder: "Description of article" %>
          </div>
        </div>

   <div class="text-center mt-4" >
          <%= f.submit class: "btn btn-outline-success form-search" %>
        </div>
      <% end %>
    </div>

     </div>
</div>
    

app/views/articles/edit.html.erb
<div class="article-index">
<h1 class="mt-3 text-center">Editing article</h1>

<%= render "form", article: @article %>
 <div class="text-center mb-4">
  <%= link_to "Show this article", @article,class: "text-white btn btn-primary  index-btn" %> 
  <%= link_to "Back to articles", articles_path,class: "text-white btn btn-primary index-btn" %>
  </div>



</div>

app/views/articles/index.html.erb
<div class="article-index">
<p style="color: green"><%= notice %></p>

<h1 class="mt-3 text-center">Articles</h1>

<div class="flickr_pagination">
  <%= will_paginate @articles, list_classes: %w(pagination justify-content-center) %>
</div>

<div id="articles">
  <% @articles.each do |article| %>
  <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded card-glass">
          <div class="card-header font-italic">
             by <%= article.user.username if article.user %>
          </div>
          <div class="card-body card-glass-inner">
            <h5 class="card-title"><%= link_to article.tittle, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <% if logged_in? && (article.user == current_user || current_user.admin?) %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <div class="text-center mb-2">
  <%= link_to "New article", new_article_path, class:"btn btn-outline-dark" %>
  </div>
</div>

<div class="flickr_pagination">
  <%= will_paginate @articles, list_classes: %w(pagination justify-content-center) %>
</div>
</div>

app/views/articles/new.html.erb
<div class="article-index">
<h1 class="mt-3 text-center">New article</h1>

<%= render "form", article: @article %>
 <div class="text-center mb-4">
 
  <%= link_to "Back to articles", articles_path,class: "text-white btn btn-primary index-btn" %>
  </div>

</div>

app/views/articles/show.html.erb
<div class="show-index">
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div class="text-center">
  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
  <%= link_to "Edit this article", edit_article_path(@article),class: "text-white btn btn-primary  index-btn" %> 
  <%= link_to "Back to articles", articles_path ,class: "text-white btn btn-primary  index-btn"%>
  <% end %>
  <% if logged_in? && (@article.user == current_user || current_user.admin?) %>
  <%= link_to "Destroy this article", @article,data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  },class: "text-white btn btn-primary  index-btn" %>
  <% end %>
</div>
</div>