config/routes.rb
Rails.application.routes.draw do
  resources :categories
  
  resources :articles
  root 'home#index'
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/views/layouts/_header.html.erb
 <nav class="navbar navbar-expand-lg bg-dark-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="/">My-Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active text-white" aria-current="page" href="#">About Us</a>
        </li>
        <li class="nav-item">
          <a class="nav-link text-white" href="/articles">Blogs</a>
        </li>
         <li class="nav-item"> 
        <%= link_to "Bloggers", users_path, class: "nav-link text-white" %>
      </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu dropper">
            <% if logged_in? %>
            <%= link_to "Create new article", new_article_path, class: "dropdown-item text-white" %>
          <% end %>  
            <%= link_to "View articles", articles_path, class: "dropdown-item text-white" %>
          </ul>
        </li>
        <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           <%= "(Admin)" if current_user.admin? %> Profile [<%= current_user.username %>]
          </a>
          <ul class="dropdown-menu dropper">
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item text-white" %>
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item text-white" %>
             <%= link_to "Delete profile", user_path(current_user), class: "dropdown-item text-danger",data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %> 
          </ul>
        </li>
        <% end %>
         <% if logged_in? %>
        
        <li class="nav-item">
          <%= link_to 'Logout', logout_path, class: "nav-link text-white", data: {
                    turbo_method: :delete
                  }  %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link text-white" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link text-white" %>
        </li>
      <% end %>
 
      </ul>
      <form class="d-flex " role="search">
        <input class="form-control me-2 index-form" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_messages.html.erb
  <% flash.each do |name, msg| %>
    <div class=" mb-0 alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-bs-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     <%= stylesheet_link_tag 'custom', media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_importmap_tags %>
  </head>

  <body class="d-flex flex-column">
    <%= render "layouts/header" %>
  
      <%= render 'layouts/messages' %>
      <%= yield %>
    
   <footer id="sticky-footer" class="flex-shrink-0 py-4 bg-dark text-white-50">
      <div class="container text-center text-white">
      <small>Copyright &copy; Mudit Gupta</small>
    </div>
    </footer>
  </body>
</html>